"""add warehouses stock transfers cashbox transfers supplier_id

Revision ID: bb3614368490
Revises: 001_initial
Create Date: 2026-07-20 21:26:59.710474

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bb3614368490'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cashbox_transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('from_cashbox_id', sa.String(length=36), nullable=False),
    sa.Column('to_cashbox_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cashbox_transfers_from_cashbox_id'), 'cashbox_transfers', ['from_cashbox_id'], unique=False)
    op.create_index(op.f('ix_cashbox_transfers_to_cashbox_id'), 'cashbox_transfers', ['to_cashbox_id'], unique=False)
    op.create_index(op.f('ix_cashbox_transfers_transfer_number'), 'cashbox_transfers', ['transfer_number'], unique=True)
    op.create_index(op.f('ix_cashbox_transfers_user_id'), 'cashbox_transfers', ['user_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('movement_number', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('movement_type', sa.String(length=20), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(length=36), nullable=True),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_movement_number'), 'stock_movements', ['movement_number'], unique=True)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_user_id'), 'stock_movements', ['user_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_warehouse_id'), 'stock_movements', ['warehouse_id'], unique=False)
    op.create_table('stock_transfers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('transfer_number', sa.String(length=50), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('from_warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('to_warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_transfers_from_warehouse_id'), 'stock_transfers', ['from_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_product_id'), 'stock_transfers', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_to_warehouse_id'), 'stock_transfers', ['to_warehouse_id'], unique=False)
    op.create_index(op.f('ix_stock_transfers_transfer_number'), 'stock_transfers', ['transfer_number'], unique=True)
    op.create_index(op.f('ix_stock_transfers_user_id'), 'stock_transfers', ['user_id'], unique=False)
    op.create_table('warehouse_stocks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('warehouse_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_stocks_product_id'), 'warehouse_stocks', ['product_id'], unique=False)
    op.create_index(op.f('ix_warehouse_stocks_warehouse_id'), 'warehouse_stocks', ['warehouse_id'], unique=False)
    op.create_table('warehouses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouses_name'), 'warehouses', ['name'], unique=True)
    op.add_column('products', sa.Column('supplier_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_products_supplier_id'), 'products', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_products_supplier_id'), table_name='products')
    op.drop_column('products', 'supplier_id')
    op.drop_index(op.f('ix_warehouses_name'), table_name='warehouses')
    op.drop_table('warehouses')
    op.drop_index(op.f('ix_warehouse_stocks_warehouse_id'), table_name='warehouse_stocks')
    op.drop_index(op.f('ix_warehouse_stocks_product_id'), table_name='warehouse_stocks')
    op.drop_table('warehouse_stocks')
    op.drop_index(op.f('ix_stock_transfers_user_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_transfer_number'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_to_warehouse_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_product_id'), table_name='stock_transfers')
    op.drop_index(op.f('ix_stock_transfers_from_warehouse_id'), table_name='stock_transfers')
    op.drop_table('stock_transfers')
    op.drop_index(op.f('ix_stock_movements_warehouse_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_user_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_number'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_cashbox_transfers_user_id'), table_name='cashbox_transfers')
    op.drop_index(op.f('ix_cashbox_transfers_transfer_number'), table_name='cashbox_transfers')
    op.drop_index(op.f('ix_cashbox_transfers_to_cashbox_id'), table_name='cashbox_transfers')
    op.drop_index(op.f('ix_cashbox_transfers_from_cashbox_id'), table_name='cashbox_transfers')
    op.drop_table('cashbox_transfers')
    # ### end Alembic commands ###
